//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CelicniProfili.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mon_opis
    {
        public int ID_mono { get; set; }
        public int No_node { get; set; }
        public double Node_x { get; set; }
        public double Node_y { get; set; }
        public int index_pr { get; set; }
    }
}
