//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CelicniProfili.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class monoblok_pozicije_ojačanja
    {
        public int ID_mono { get; set; }
        public double X_pos { get; set; }
        public double Y_pos { get; set; }
        public int br_segment { get; set; }
        public string pravac { get; set; }
        public int index_pr { get; set; }
    }
}
