//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CelicniProfili.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ojačanje_opis
    {
        public int index_pr { get; set; }
        public int Id_ojač { get; set; }
        public double b { get; set; }
        public double h { get; set; }
        public double pol_x { get; set; }
        public double pol_y { get; set; }
    }
}
