//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CelicniProfili.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class profil
    {
        public int ID { get; set; }
        public int ID_monoblok { get; set; }
        public int ID_ojačanje { get; set; }
        public Nullable<double> pos_x { get; set; }
        public Nullable<double> pos_y { get; set; }
    
        public virtual Monoblok Monoblok { get; set; }
        public virtual Profil_I_karakteristike Profil_I_karakteristike { get; set; }
    }
}
