//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CelicniProfili.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tip_monoblok
    {
        public int id_tip { get; set; }
        public string tip { get; set; }
        public int id_tehn { get; set; }
    
        public virtual tehnologija_monoblok tehnologija_monoblok { get; set; }
    }
}
